version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 5s
      retries: 30
    networks:
      - app-network
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "wait-for db:5432 --timeout=90 &&
             alembic upgrade head &&
             python seed.py &&
             uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT}"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge